### ISSUE TITLE
Document dependencies for running the build

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/java-cookie#15]
The build requires npm, grunt and bower to be installed globally:

```shell
npm install grunt -g
npm install bower -g
```

**Comment by tholu** [comment]
@FagnerMartinsBrack No, it doesn't after merging #18 - `grunt` was an unneeded dependency I removed. The necessary dependencies (node, npm, bower) should also be installed via the `frontend-maven-plugin` plugin.

**Comment by tholu** [comment]
@FagnerMartinsBrack This can be closed now, everything is documented in the [Contributing Guidelines](https://github.com/js-cookie/java-cookie/blob/master/CONTRIBUTING.md).

**Comment by FagnerMartinsBrack** [comment]
Thanks @tholu
