### ISSUE TITLE
JSON get does not handle missing cookie

### ISSUE THREAD

**Issue by literakl** [js-cookie/java-cookie#16]
public synchronized String get(String name) returns null when cookie is not present. The JSON variant does not checks returned value and passes null to object mapper where NPE is thrown.

public <T> T get(String name, Class<T> dataType) throws CookieParseException {
        String value = this.get(name);
        try {
            return this.mapper.readValue(value, dataType);
        } catch (IOException var5) {
            throw new CookieParseException(var5);
        }
    }

**Comment by tholu** [comment]
@literakl What do you expect if the cookie is missing? You can also wrap this with `Optional.ofNullable()` yourself to handle it properly.

**Comment by literakl** [comment]
Please read the attached code. There is a bug because there is no null check. It should be:

String value = this.get(name);
**if (value == null) return null;**
try {
return this.mapper.readValue(value, dataType);
} catch (IOException var5) {
throw new CookieParseException(var5);
}

**Comment by tholu** [comment]
@literakl Sorry, I missed that. It helps when you format your code 😉 As I‘m currently fixing some stuff here, I‘ll try to fix this as well.
