### ISSUE TITLE
openjdk-11.0.2: org.jboss.modules.ModuleNotFoundException: java.se error using mvn verify

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/java-cookie#20]
See https://github.com/js-cookie/java-cookie/pull/19#issuecomment-468227230 for context

**Comment by JevinMenezes** [comment]
Have updated multiple dependencies and tests are successful for jdk12 locally
Travis builds for openjdk 8,9,10,11,12,13,14 are also successful

**Comment by JevinMenezes** [comment]
Travis CI build for openjdk version "11.0.2" are passing
