### ISSUE TITLE
🚨🚨🚨REQUEST FOR MAINTAINERS🚨🚨🚨

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/java-cookie#26]
I started this project a long time ago in a time where I was working with Java Servlets in the hope that I could keep up with the changes in js-cookie. It turns out I don't code in Java anymore, the code in this repository didn't keep it up with the js-cookie API, and there are a few issues that need to be fixed and Pull Requests that need to be reviewed.

If you are interested in becoming a maintainer of this project, please get in touch by replying to this thread.

**Comment by JevinMenezes** [comment]
I can become a maintainer of this project

**Comment by FagnerMartinsBrack** [comment]
Hi @JevinMenezes, I've invited you. Please make sure all tests pass, local configs don't leak through the source control, etc.
It's been a long time since I used Maven so I'll need some guidance on how to give you the necessary authorizations to publish to the Maven repository.

The idea of this project was to keep the API consistent with js-cookie but in Java classical OOP manner, it turns out we changed js-cookie but I couldn't keep up with this project.

Feel free to adapt the API if you want, as long as we make sure the changelogs respect SEMVER, etc :)

Let me know when you accept the invitation to make sure you've got all necessary permissions on this repo.

Cheers.

**Comment by JevinMenezes** [comment]
Hi @FagnerMartinsBrack thanks for the invitation and I've accepted the invite. I would be keeping up with all the top GitHub best practices for developers. I'm well-versed in using Maven tool and no worries on Maven repository related stuff.

Finally, I'm enthused to be a maintainer of this repository.

Cheers mate.
