### ISSUE TITLE
Publish on maven central

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/java-cookie#3]
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by cfrancis-oo** [comment]
Agreed, should be able to pull from maven

**Comment by FagnerMartinsBrack** [comment]
Created an issue as requested by the [guide](http://central.sonatype.org/pages/ossrh-guide.html#create-a-ticket-with-sonatype) for new projects: https://issues.sonatype.org/browse/OSSRH-16716

**Comment by FagnerMartinsBrack** [comment]
### Steps taken to be able to upload to Maven Central

#5: Add meta-data requirements for deployment on Maven Central
#6: Change the artifactId to express the project hosting
#7: Change the package names to be specific for where the project comes from

### How to setup the release process

Add the following information in maven `settings.xml` file (`%USERPROFILE%/.m2/settings.xml` in Windows):

**Server config:**

``` xml
<servers>
  <server>
    <id>java-cookie-scm</id>
    <username>GITHUB_USERNAME</username>
    <password>GITHUB_PASSWORD</password>
  </server>
  <server>
    <id>ossrh</id>
    <username>JIRA_USERNAME</username>
    <password>JIRA_PASSWORD</password>
  </server>
</servers>
```

**Profile config:**

``` xml
<profiles>
  <profile>
    <id>release</id>
    <activation>
      <activeByDefault>true</activeByDefault>
    </activation>
    <properties>
      <gpg.executable>gpg2</gpg.executable>
      <gpg.passphrase>GPG_PASSPHRASE</gpg.passphrase>
    </properties>
  </profile>
</profiles>
```

### How to execute the release

Execute the following command:

``` shell
$ mvn release:clean release:prepare release:perform
```

If the only thing needed is deploy to maven central, execute the following command:

``` shell
$ mvn deploy -P release
```

**Comment by FagnerMartinsBrack** [comment]
@cfrancis-oo it's there ^^:

``` xml
<dependency>
  <groupId>com.github.js-cookie</groupId>
  <artifactId>java-cookie</artifactId>
  <version>0.0.2</version>
</dependency>
```

**Comment by cfrancis-oo** [comment]
Amazing! Thanks @FagnerMartinsBrack
